# Generated by Django 3.1 on 2020-09-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20200904_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
