# Generated by Django 3.1 on 2020-09-15 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_endpoint_mlalgorithm_mlalgorithmstatus_mlrequest_userinputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlalgorithm',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 15, 16, 11, 9, 163509)),
        ),
        migrations.AddField(
            model_name='mlalgorithmstatus',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
