# Generated by Django 3.1 on 2020-09-15 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20200915_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlalgorithm',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
