# Generated by Django 3.1 on 2020-10-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20201001_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='stars',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
